AWSTemplateFormatVersion: '2010-09-09'

Resources:
  EKSCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: 'hieuvm5-cluster'
      ResourcesVpcConfig:
        SubnetIds:
        - subnet-0dcdc62e419dcbb63
        - subnet-0ca6a105e7aa18d2e
        SecurityGroupIds:
          - sg-0535a283ab3aa9d1f
      RoleArn: arn:aws:iam::433017143701:role/eksClusterRole
      Version: '1.28'  # Specify the desired Kubernetes version

  NodeGroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: !Ref EKSCluster 
      NodegroupName: 'hieuvm5-node_group'
      Subnets:
        - subnet-0dcdc62e419dcbb63
        - subnet-0ca6a105e7aa18d2e
      ScalingConfig:
        MinSize: 1
        MaxSize: 3
        DesiredSize: 2
      InstanceTypes:
        - t4g.medium
      AmiType: AL2_ARM_64
      NodeRole: arn:aws:iam::433017143701:role/EKS_WORKER_NODE_ROLE
